<script setup>
import { useI18n } from 'vue-i18n';
const { t } = useI18n();

</script>

<template>
  <div class="current">
    <h1>Les coccinelles de 2067</h1>
    <h3>Maïka Hebert</h3>
    <br>
    <p>En 2067, à Montréal, on célèbre le centenaire de l’Expo 67. On a les soirées chargées de galas de  luxe, de concerts d’artistes étrangers, de spectacles de stripteaseurs. On cherche à revivre la  festivité collective du passé dans cette ère tiède qui tend vers la monotonie. On veut de l’exotique,  du lointain, de l’inconnu, de la débauche. On n’attendait que ça pendant des décennies, l’occasion  de festoyer. C’est beau tout ça, dans le fond. Faut savoir que c’est beau. Et faut se le montrer. Mais  juste à nous. Parce que cette joie nous appartient tant qu’on la produit ici. Faite au Québec. <em>Made  in Quebec</em>.  </p><br>
    <p>On offre des séjours en hôtel à bas prix. Déjeuner inclus. N’importe qui peut loger n’importe où.  Logements luxueux deviennent hôtels. Les propriétaires comprendront, les locataires  pardonneront. Au fil des années, les locataires des résidences olympiques ont été évacués pour la  cause. Une bonne cause. On a les yeux grands. La panse, on ne sait pas encore. En fait, on s’en  contrefout. Tant qu’on s’amuse.  </p><br>
    <p>On investit quatre-vingt-treize beaux milliards dans la STM. Des métros, on en flanque partout ! À Saint-Jérôme, le métro ! Et à Saint-Hyacinthe et à Vaudreuil et à Saint-Jean-sur-Richelieu ! On  colore la carte comme des enfants de maternelle avec des <em>Crayola</em> et une créativité excessive. On  bat l’arc-en-ciel avec neuf couleurs de lignes. On inaugure la ligne indigo trois jours après avoir  baptisé la ligne bourgogne. Personne l&#39;aime, ce nom, mais on fait la fête, alors personne n’en dit  quoi que ce soit. C’est pas donné de vivre ici. Mais, pas de problème, on se crève les poches.  </p><br>
    <p>Dans le fond, on se paye notre propre fête. Donc personne ne se plaint. On est comme des grands, les Québécois. On a vieilli, on a mûri, on s’est attendri comme une bonne pièce de steak, on est  flambant et fringuant et libre ! Bon, non, on n&#39;est pas indépendant, mais c’est presque ça. </p><br>
    <p>Jean-Drapeau ressemble à une étoile qui se consume avec avarice et voracité, qui brille de son plus  fort avant de se ravaler en trou noir et de tout raser. Tout engloutir. Mais l’astronomie n’a pas sa  place ici. Ici, on fait la fête. C’est 2067, faut célébrer ça ! Ce qu’on rase, c’est nos barbes et nos  mollets et nos pubis. Ce qu’on engloutit, c’est des festins cochons et la rationalité qui bride nos  ardeurs. Ce qu’on ravale, c’est nos appréhensions du futur et quelconque considération autre que  de faire le <em>party</em>.  </p><br>
    <p>Seul hic, monsieur le premier ministre a décidé que notre célébration allait être 18+. Juste des  adultes. C’est plus simple au niveau légal. Moins de chances de progression soudaine et ingérable  de prostitution infantile en un été. Parce que ça ne dure qu’un été. On a le droit à un été. Donc, on  va faire ça bien. Le trafic d’enfants attendra.<br>De toute façon, les proxénètes et leurs prostituées nous en veulent déjà depuis qu’on a criminalisé  l’avortement en 2027. Leurs filles en ont marre de devoir se vider le ventre dans des cliniques pas  nettes au noir. Leurs clients sont agacés de se faire demander de plus en plus souvent de mettre un  condom. Peu importe. Qu’ils s’arrangent, les criminels. Les Québécois sont des gens bien qui  veulent juste s’amuser et faire la fête.  </p><br>
    <p>C’est le centenaire de l’Expo 67. On ne va pas laisser notre progéniture nous gâcher ça. Pas  d’enfants ? Mais pas de soucis, franchement. On a les camps de jour pour ça. On le fait depuis  toujours. Été après été. C’est une industrie florissante. Il y a bien du choix. Tout le monde place  leurs enfants là et c’est réglé, on n’y pense déjà plus.  </p><br>
    <p>* * *  </p><br>
    <p>Le camp de jour <em>Renessence</em> pour les 8 à 12 ans est situé au Lac-Clair, où on n’a pas encore ajouté  de ligne de métro. Peut-être qu’on la nommerait vermillon celle-là. Peu importe. On entasse 700  jeunes dans des bus voyageurs et on les expédie à la campagne, autour d’un lac en pleine forêt,  pour apprendre sur la vie. Et ça nous criss la sainte paix. Comme ça, ça va être notre tour  d’annihiler le silence. On ne va plus être les victimes, les parents épuisés à deux décibels du  <em>burnout</em>, on va être les bourreaux de la paix. On fout le feu nous-même, on gribouille sur les murs,  on s’affole comme des enfants sur un <em>rush</em> de sucre. Sauf qu’on a notre propre sucre, les adultes. </p><br>
    <p>Les moniteurs prennent bien soin des garnements. Les camps roulent comme dans du beurre, de  vraies colonies de fourmis où l’on sert avoine, miel et fruits pour déjeuner avec du jus d’orange  pressé du matin et filtré de sa pulpe pour causer le moins de grimaces dédaigneuses possible. Des  lasagnes gratinées encore fumantes sont servies pour souper, puis des gâteaux aux carottes coupés  carré, deux pouces par deux pouces, pour que ça soit équitable, pour dessert. Des épis de maïs  miniatures baignent dans du vinaigre, prêts à être dévorés. Des sacs de macédoine jardinière  attendent, congelés en quantité industrielle pour durer toute la saison. Bref, ça mange bien. Et à  voir l&#39;argent déboursé, il faut bien. </p><br>
    <p>Les p’tits monstres bénéficient d’une attention constante et d’une animation continuelle ; ils n’ont  pas le temps de s’ennuyer. Le matin, après le copieux déjeuner, quand tout le monde a le ventre  arrondi et se frotte encore les yeux, ils marchent dans la forêt en chantant jusqu’au lieu de  rencontre, une clairière approvisionnée de huttes. Ils écoutent les moniteurs avec attention.  Ensuite, ils sont divisés en groupes avec leur superviseur assigné pour tester une panoplie  d’activités estivales. Kayak, survie en forêt, hébertisme, canot, tir à l’arc, escalade de paroi  rocheuse, pédalo. Y’a de quoi s’occuper jusqu’au dîner, puis, une fois les assiettes vides empilées  dans des bacs, de quoi s’occuper jusqu’au souper. Finalement, l’animation de soirée débute. C’est  ce que les enfants préfèrent.<br>C’est le tour du groupe E d’avoir un feu de camp. Tout le monde, 37 jeunes et leurs deux moniteurs,  se serre autour du feu, sous les étoiles, entre les sapins, un berlingot de lait et un muffin aux bleuets  tout chaud sorti du four en main. Les moniteurs racontent une histoire. À chaque soir. À chaque  feu. Une nouvelle histoire à chaque lune. Ils ne se lassent pas de l’activité. Les enfants en raffolent.  Ils chahutent, frémissant d&#39;excitation, petits doigts encore potelés resserrés avec possessivité  autour de leur muffin. Le cœur moelleux débordant de vapeur s’affaisse et les mord sous les ongles,  mais ils n’y portent pas attention. L’histoire va commencer. <em>Shh</em>, ils font le signe du silence. </p><br>
    <p><em>« Il était une fois une vieille dame. Une écrivaine dans Hochelaga, Montréal. Son adresse, c’est  le 13 sur rue Amyot et Rouen, près du charmant parc Lalancette. Le quartier de l’écrivaine est  paisible et irréprochable. Sa résidence, on pourrait difficilement la qualifier pareillement. Depuis  qu’elle y habite, l’endroit est infesté de coccinelles, été comme hiver. Une quantité considérable  d’insectes décède, affectée par le froid ou le chaud ou le vent du nord traînant avec lui des  pesticides. Ces cadavres se mêlent aux vivants. Ils adhèrent solidement aux murs que grimpent les  insectes intacts. Ils saturent les gouttières. Ils forment un tapis presque uniforme à l’entrée. Une  odeur infecte se dégage de ce bordel.</em>  </p><br>
    <p><em>La dame ne semble aucunement perturbée par l’état catastrophique de l’invasion. Ou si elle l’est,  personne ne peut le savoir parce qu’elle ne sort jamais de sa demeure. Elle y reste, emmurée,  tapant frénétiquement sur sa machine à écrire. Sur sa table de cuisine, un amoncellement de  papiers mélangés, de récits qui se confondent, de personnages distincts qui s’entrechoquent. Une  tasse de café tiède à sa gauche trône sur un morceau de manuscrit agrafé maladroitement. À la  surface, une coccinelle flotte, ailes dissoutes par l’acidité du café noir. L’écrivaine ne s’arrête que  pour réchauffer sa caféine au micro-ondes. La coccinelle cuit sous la radiation électromagnétique.  Ses intérieurs délicats, comme le liquide infusé où elle trempe, bouillonnent.</em>  </p><br>
    <p><em>Après s’être pincée le bout de la langue sur du café trop chaud, l’écrivaine se frustre avec les  caractères étampés sur la feuille. Ils osent fausser à l’occasion et elle ne supporte plus de les  corriger. De toute façon, elle n’affectionne pas son idée du matin même. Elle ne parvient pas à la  faire aboutir. Elle a toujours été incapable de coudre une prose qui se complète. Elle refuse de  s’en inquiéter. C’est une écrivaine, elle l’a décrété. Un jour, elle signera un manuscrit complet,  final. Jusque-là, ça sera café noir aux coccinelles. Elle chemine paisiblement. Son cimetière de  récits s’engraisse. Cela ne l’effraie pas. Ses œuvres dépourvues de fin se valent quand même dans  son cœur.</em>  </p><br>
    <p><em>Toutes ces pages incomplètes sont entreposées au sous-sol dans des boîtes grugées par les  rongeurs immiscés entre les murs. On y retrouve aussi des coccinelles mortes, logées entre les  pages. L’écrivaine ne peut supporter la vue de son travail non terminé trop longtemps. Elle s’en  débarrasse de cette façon, chasse de son esprit le tourment de l’inaccompli et des pages blanches.  Tout ça est dissimulé hors de sa vue pour qu’elle n’ait jamais à y repenser. Ses rejetons sont</em><br><em>étouffés là, fourrés dans ce néant vaseux, dépareillés et essorés de la vie dont l’écrivaine les  avaient imbibés.</em>  </p><br>
    <p><em>Ici-bas, ils fécondent dans cette opacité rance et fertile, ils pullulent. De ces maudites boîtes  jaillissent des monstres élevés par l’abandon, vacillant entre la vie et la mort comme ces  coccinelles au café. Ils ne grimpent jamais jusqu’à l’écrivaine et se dissimulent dans leurs boîtes  respectives quand elle descend leur livrer des compagnons reniés. Ils n’attaquent pas leur  fondatrice ; ils font pire. Ils la hantent. Aux catacombes de son esprit, ils s’enracinent. Ils la  troublent, la rongent mieux que des rats, des mites, des mauvaises herbes, des pestes, des  coccinelles. Ils lui font pendre les paupières et fondre la peau. Ils la dépouillent de ses couleurs et  lui dégarnissent la chevelure. L’écrivaine a à la fois 23 et 90 ans. Son corps est usé par ses démons  qui prospèrent malgré elle depuis qu’elle est enfant.</em>  </p><br>
    <p><em>À 14 ans, elle a osé l’offense originelle. Sa première histoire, celle sur laquelle elle s’est obstinée  le plus, celle qui a frôlé la complétude. La vision était innocente, marquée de l’imaginaire enfantin  intact propre à une fillette. Une armée de coccinelles. Un arc-en-ciel qui gonfle parmi les nuages,  pointillant le ciel. Des étoiles diurnes. Les bêtes du bon Dieu. Comme une vraie déesse vénérée,  l’écrivaine s’en est lassé. Frustrée, elle a froissé les feuilles barbouillées de ses rêveries et les a  mises au ban dans une boîte à chaussures. L’abattoir a initialement été inauguré dans le placard  de sa maison d’enfance. Une après l’autre, les chimères se sont empilées.</em>  </p><br>
    <p><em>Pourtant, l’histoire originelle demeure à jamais la plus palpable. Seule elle a franchi la brèche du  réel. La vie qui anime sa création est tirée d’elle, puisée dans sa jeunesse. Ce sort, elle ne peut y  échapper. Parce que son péché premier ne sera jamais excusé. Peu importe combien de fois elle  essayera. Peu importe toutes les pages qu’elle souillera de son encre blasphématoire, toutes ses  tentatives de se renouveler, il se perpétuera. Elle boira du café noir aux coccinelles jusqu’à sa  mort Jusqu’à ce que son cœur précocement vieilli étouffe sous le poids des échecs, sous le souvenir  inévitable des monstruosités dans ses boîtes. On la trouvera morte, séchée comme un raisin et  dévorée par la pourriture, à côté d’un café tiède. Une coccinelle sur le nez. »</em>  </p><br>
    <p>Le feu crépite. Les enfants n’échappent pas immédiatement à leur silence stupéfait et captivé. Ils  sont pendus aux lèvres du moniteur. Il boucle le récit d’une simple conclusion, comme un joli  nœud sur un cadeau d’anniversaire. <em>Et ça, les enfants, c’est pour ça que c’est illégal, l’avortement.</em>  Bourdonnement d’approbation chez les jeunes et de dégoût à la mention de la procédure. Les  moniteurs s’esclaffent et attrapent leurs sacs. Les enfants gazouillent le temps que le prochain acte  se prépare. Ils attendent avec impatience. Ça y est, les moniteurs ont des feuilles cartonnées en  main et une tablette intelligente. Ils sont prêts. Ils regagnent l’attention générale et commencent  leur démonstration.<br>Après l’histoire, comme prévu au menu, ils regardent des photos de fœtus à différents stades. Ils  les nomment « bébé », « enfant » ou « progéniture » et non « embryon », « grappe de cellules » ou  « gamètes fusionnés ». <em>C’est ce que les pro-choix disent. Pas nous.</em> La distinction est cruciale. Ils  visionnent la vidéo d’un avortement risqué et <em>raté</em>. La femme y meurt pendant qu’on lui extirpe  son « enfant ». À ses côtés, le minuscule cadavre de sa « progéniture », recroquevillé, fripé, mort  et âgé de trop de mois. Un « bébé » bombé de chair, brûlé d’acide, troué de têtes de cintres et de  têtes de phallus, engraissé de sang. La chose, le monstre, l’anomalie est étouffée dans un <em>ziplock</em>  et jeté à la poubelle, le corps raidi par le meurtre. La mère, dépouillée de six livres, puis de 21  grammes, est déplacée hors de la chambre pour faire de l’espace. Les enfants ont différentes  théories sur ce qu’on fait d’elle. Soit elle est remise à l’homme qui la traînait dans la salle au début  de la vidéo, soit on en dispose dans les ordures pour qu’elle se réveille ridée, vieillie et  accompagnée de sa chimère, soit elle est livrée directement au diable comme elle le mérite. Les  moniteurs leur disent qu’on ne le saura décidément jamais. La vidéo se poursuit. L’instrument de  métal utilisé est brièvement récuré dans l’évier. Puis, une autre femme terriblement enceinte entre  en haletant de sanglots. Les enfants s’excitent à l’idée d’assister à une autre procédure encore plus  immorale. À leur déception, les moniteurs annoncent qu’ils gardent cet épisode pour plus tard.  </p><br>
    <p>Partout au Québec, des superviseurs de camp introduisent l’anatomie féminine aux enfants comme  une boucherie. Les garçons scrutent les fillettes, les inspectent à coup de doigts sur la poitrine, de  mains dans les jolies culottes à fleur que maman leur a achetées. La nuit, elles se touchent,  hésitantes, et se répugnent. Le jour, elles se font discrètes jusqu’à ce qu’on oublie les révélations  du feu de camp. Jusqu’à la prochaine histoire. Jusqu’à la prochaine vidéo qui rafraîchira les  méninges. Celles qui daignent s’enfuir, s’égarer dans la forêt, horrifiées par leur traitement et leur  découverte et leur propre corps, sont éventuellement retrouvées par des moniteurs qui, profitant de  l’intimité des bois, s’engagent à leur enseigner quelques notions manquantes aux vidéos.  </p><br>
    <p>Des 300 fillettes de 8 à 12 ans accueillies au camp <em>Renessence</em> durant l’été festif de 2067, 28  reviendront avec un ventre enflé, gorgé de viol. À travers la province, 300 000 enfants passent cet  été en camp de jour et 13 000 fillettes portent les semences des moniteurs, des membres de la  direction des camps ou de leurs jeunes collègues masculins. Peu mèneront à terme leur grossesse.  Certaines mourront. Certaines seront contraintes par leurs parents à avorter illégalement. Certaines  mourront de peur sur les chaises de gynécologie improvisées et précaires, jambes bien écartées,  vision brouillée de larmes et d’anxiolytiques qui saturent leur petit système tout neuf. Certaines se  videront de leur sang en expulsant le parasite qui a grugé de leurs os le gras, la chair, la vie.  </p><br>
    <p>Pourtant, certaines auront cet être qu’on leur a imposé, il se faufilera hors de cet endroit étroit,  creux et oppressant où on l’a inséré et connaîtra la lumière des néons, la blancheur hospitalière.  Et, s’il entend le grognement des parents au fond de la chambre, le prix salé de l’hospitalisation  privée.<br>Ces parents justement, oui, tous ces parents, que dire d’eux ? Globalement contentés par le fameux  <em>party</em> que les camps de jour leur ont offert, ils n’émettent aucune plainte. Sinon, ils seraient mis  dans l’embarras. Ça serait ben emmerdant si le fédéral investiguait, si le personnel des camps était  incriminé et si on n’avait nulle part où placer les morveux l’été quand on veut juste baiser dans la  piscine olympique et se faire quelques lignes de coke question que le ciel ait la même lueur joviale  que dans les camps, avant qu’on soit nous-même inséminé d’un enfant, celui qu’on expédie dans  le lieu de son origine pour qu’il apprenne un peu sur la vie. On l’a vécu, ce traumatisme. Et on y a  survécu, alors notre « progéniture » survivra, elle aussi. Le cycle perdure, on en a oublié la  provenance, le début. On l’alimente, on le ravitaille de nouvelle chair parce que c’est tout ce qu’il  veut bien manger, la canaille. Difficile à rassasier.  </p><br>
    <p>Les patrons de l’industrie du sexe, éternellement enragés contre le gouvernement, échouent encore  cette année. Ils ravitaillent les camps de jour de leur personnel sadique, assurent la ruine des  générations qui se succèdent depuis des décennies et tentent sans relâche d’enfler artificiellement  la nécessité des avortements pour renverser les lois. Mais l’échec est cuisant. Surtout cette année.  Bien que leurs inséminations concluantes aient presque doublé cette saison, leurs efforts passent  encore inaperçus. Le Québec a la gueule de bois. Il en revient encore petit à petit de son esti de  bon <em>party</em>. Il veut juste des <em>Advil</em> et un verre d’eau du robinet bien froide. L’eau québécoise, y a  rien de meilleur ! Peu importe si notre fillette pis celle du voisin pis celle de la voisine sont toutes  dues pour accoucher cet avril. Peu importe si elles cauchemardent toutes en même temps à une  machine à écrire, des rides et des coccinelles. On a pu s’amuser, c’est ce qui importe. On se donne  rendez-vous dans 100 ans. </p><br>

  </div>
</template>

<style>
.current {
  text-align: left;
}
</style>
